name: Check

on:
  push:
    branches-ignore:
      - main
  workflow_call:

permissions:
  contents: read

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Run checks
        run: nix develop --impure --command check
